namespace: "chrismeyersfsu"
name: "ansible_content_example"
version: "0.0.1"
description: "a collection for testing ansible collections"
authors: ["Chris Meyers"]
license:
  - "GPL-3.0-or-later"
readme: "README.md"
homepage: "https://github.com/chrismeyersfsu/ansible-content-example"
tags:
  - collectiontest
dependencies: {}
